import{a as h,i as n,S as f}from"./assets/vendor-BeB49kps.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const u of s.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&r(u)}).observe(document,{childList:!0,subtree:!0});function a(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function r(e){if(e.ep)return;e.ep=!0;const s=a(e);fetch(e.href,s)}})();const p="46156366-74388488ea9228d7ab1fb8713",L="https://pixabay.com/api/";async function m(o,t=1){const a=`${L}?key=${p}&q=${o}&image_type=photo&orientation=horizontal&safesearch=true&page=${t}&per_page=15`;try{return(await h.get(a)).data}catch(r){console.error("Error fetching images",r)}}function y(o){const t=document.querySelector(".gallery"),a=o.map(r=>`
    <a href="${r.largeImageURL}" class="gallery-item">
      <img src="${r.webformatURL}" alt="${r.tags}" loading="lazy" />
      <div class="info">
        <p><b>Likes:</b> ${r.likes}</p>
        <p><b>Views:</b> ${r.views}</p>
        <p><b>Comments:</b> ${r.comments}</p>
        <p><b>Downloads:</b> ${r.downloads}</p>
      </div>
    </a>
  `).join("");t.insertAdjacentHTML("beforeend",a)}const b=document.querySelector("#search-form"),g=document.querySelector(".gallery"),d=document.querySelector(".load-more");let l="",i=1,c=0;b.addEventListener("submit",w);d.addEventListener("click",S);async function w(o){if(o.preventDefault(),l=o.target.elements.searchQuery.value.trim(),!l){n.warning({title:"Warning",message:"Please enter a search query."});return}i=1,g.innerHTML="",d.classList.add("is-hidden"),document.querySelector(".loader").classList.remove("is-hidden");try{const t=await m(l,i);if(c=t.totalHits,c===0){n.error({title:"Error",message:"No images found. Please try again."});return}y(t.hits),new f(".gallery a").refresh(),c>15&&d.classList.remove("is-hidden")}catch{n.error({title:"Error",message:"Something went wrong. Please try again."})}finally{document.querySelector(".loader").classList.add("is-hidden")}}async function S(){i+=1,document.querySelector(".loader").classList.remove("is-hidden");try{const o=await m(l,i);y(o.hits),new f(".gallery a").refresh();const t=Math.ceil(c/15);i>=t&&(d.classList.add("is-hidden"),n.info({title:"Info",message:"We're sorry, but you've reached the end of search results."})),v()}catch{n.error({title:"Error",message:"Something went wrong. Please try again."})}finally{document.querySelector(".loader").classList.add("is-hidden")}}function v(){const{height:o}=g.firstElementChild.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
