import{a as h,i as a,S as f}from"./assets/vendor-BeB49kps.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const u of s.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&r(u)}).observe(document,{childList:!0,subtree:!0});function n(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function r(e){if(e.ep)return;e.ep=!0;const s=n(e);fetch(e.href,s)}})();const p="46156366-74388488ea9228d7ab1fb8713",b="https://pixabay.com/api/";async function g(o,t=1){const n=`${b}?key=${p}&q=${o}&image_type=photo&orientation=horizontal&safesearch=true&page=${t}&per_page=15`;try{return(await h.get(n)).data}catch(r){console.error("Error fetching images",r)}}function m(o){const t=document.querySelector(".gallery"),n=o.map(r=>`
    <a href="${r.largeImageURL}" class="gallery-item">
      <img src="${r.webformatURL}" alt="${r.tags}" loading="lazy" />
      <div class="info">
        <p><b>Likes:</b> ${r.likes}</p>
        <p><b>Views:</b> ${r.views}</p>
        <p><b>Comments:</b> ${r.comments}</p>
        <p><b>Downloads:</b> ${r.downloads}</p>
      </div>
    </a>
  `).join("");t.insertAdjacentHTML("beforeend",n)}const w=document.querySelector("#search-form"),y=document.querySelector(".gallery"),d=document.querySelector(".load-more");let c="",i=1,l=0;w.addEventListener("submit",L);d.addEventListener("click",v);async function L(o){if(o.preventDefault(),c=o.target.elements.searchQuery.value.trim(),!c){a.warning({title:"Warning",message:"Please enter a search query."});return}i=1,y.innerHTML="",d.classList.add("is-hidden");try{const t=await g(c,i);if(l=t.totalHits,l===0){a.error({title:"Error",message:"No images found. Please try again."});return}m(t.hits),new f(".gallery a").refresh(),l>15&&d.classList.remove("is-hidden")}catch{a.error({title:"Error",message:"Something went wrong. Please try again."})}}async function v(){i+=1;try{const o=await g(c,i);m(o.hits),new f(".gallery a").refresh();const t=Math.ceil(l/15);i>=t&&(d.classList.add("is-hidden"),a.info({title:"Info",message:"We're sorry, but you've reached the end of search results."})),P()}catch{a.error({title:"Error",message:"Something went wrong. Please try again."})}}function P(){const{height:o}=y.firstElementChild.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
